Ponder.registry((event) => {
    event.create("cti:alloy_centrifuge")
        .scene("kubejs:alloy_centrifuge", "气动合金离心机", "kubejs:alloy_centrifuge", (scene, utils) => {
            scene.showBasePlate()
            scene.world.setBlocks([3,2,3], "cti:alloy_centrifuge",false)
            scene.world.showSection([3,2,3], Direction.DOWN)
            scene.text(80, "气动合金离心机是一种能将合金离心成为合金前材料的机器\n须§9搭配匠魂炉§r使用",[3.5,2.5,3.5])
            scene.idle(70)
            scene.world.setBlocks([3,2,3], "minecraft:air",true)
            scene.idle(10)
            scene.text(30, "为了防止出现离心-合金死循环，一般搭配无法合金的镕铸炉使用")
            scene.idle(20)
            scene.world.showSection([1, 1, 1, 5, 1, 5], Direction.DOWN)
            scene.idle(5)
            scene.world.showSection([1, 2, 1, 5, 2, 5], Direction.DOWN)
            scene.idle(5)
            scene.world.showSection([1, 3, 1, 5, 3, 5], Direction.DOWN)
            scene.idle(35)
            scene.addKeyframe()
            scene.text(80, "想要气动离心机工作，其背面必须正对排液口",[0.5,2.5,3.5])
            scene.world.modifyBlock([0,2,3], (state) => state.with("facing", "east"), false)
            scene.world.showSection([0,2,3], Direction.DOWN)
            scene.idle(20)
            scene.overlay.showOutline("red", {}, [0,2,3,0,2,3], 30)
            scene.idle(40)
            scene.world.modifyBlock([0,2,3], (state) => state.with("facing", "west"), true)
            scene.idle(20)
            scene.overlay.showOutline("green", {}, [0,2,3,0,2,3], 30)
            scene.idle(60)
            scene.world.showSection([0,2,2,0,2,0], Direction.DOWN)
            scene.text(60, "接下来连接压缩空气即可，注意压强至少要7bar",[0.5,2.5,1.5])
            scene.idle(60)
    })
})
///setblock 2266 73 1210 cti:alloy_centrifuge[facing=west]{AirHandler:{Air:204784},ForgeCaps:{}}