Ponder.registry((event) => {
    event.create(["cti:quantum_miner","cti:quantum_miner_advanced"])
        .scene("kubejs:quantum_miner", "位面采矿机", "kubejs:quantum_miner", (scene, utils) => {
        scene.showBasePlate()
        scene.world.showSection([2, 1, 3, 4, 1, 3], Direction.DOWN)
        scene.text(60, "位面采矿机的原理很简单：输入压缩奇点，输出矿物")
        scene.idle(70)
        scene.text(60, "两种采矿机仅在§9采掘速度与采矿量§r上有所区别")
        scene.idle(60)
        scene.addKeyframe()
        scene.rotateCameraY(-100)
        scene.idle(20)
        scene.world.showSection([2, 1, 4, 4, 1, 6], Direction.DOWN)
        scene.text(60, "由于没有GUI，奇点只能由自动化设备输入", [3.5,1.5,5.5])
        scene.idle(90)
        scene.rotateCameraY(100)
        scene.world.showSection([2, 2, 3, 4, 2, 3], Direction.DOWN)
        scene.text(60, "之后通电，并在采矿机上方放上容器接收产物即可", [2.5,3.5,2.5])
        scene.idle(20)
        scene.world.showSection([2, 1, 2, 4, 1, 2], Direction.DOWN)
        scene.idle(40)
    })
})
///setblock 2271 72 1210 pipez:gas_pipe[down=false,east=true,has_data=false,north=false,south=false,up=false,waterlogged=false,west=true]