StartupEvents.registry("item",event=>{
    event.create("ultra_dense_nugget","basic")
    event.create("overchargedultradense","basic")
    event.create("protonium_nugget","basic")
    event.create("gas_hydrate","basic")
    event.create("graphene","basic")
    event.create("dusts_titanium","basic")
    event.create("tungsten_ingot","basic")
    event.create("halfdone_exoalloy","basic")
    event.create("pyrocrystal","basic")
    event.create("electrocrystal","basic")
    event.create("violium_alloy","basic")
    event.create("activated_matter_dust","basic")
    event.create("neutronium_singularity_press","basic").tag('thermal:crafting/dies')
    event.create("atherium_alloy","basic")
    event.create("ultra_dense_hydride_crystal","basic")
    event.create("particle_container","basic")
    event.create("clock_core","basic")
    event.create("living_control_circuit","basic")
    event.create("thermite","basic")


    event.create("dense_slag","basic")
    event.create("crystal_slag","basic")
    event.create("enriched_slag","basic")
    event.create("metal_slag","basic")
    event.create("stable_slag","basic")
    event.create("light_slag","basic")
    event.create("mineral_slag","basic")
    event.create("powdered_slag","basic")

    event.create("core_basic","basic")
    event.create("core_blaze","basic")
    event.create("core_diamond","basic")
    event.create("core_emerald","basic")
    event.create("core_harden","basic")
    event.create("core_nether","basic")


    event.create("dust_mana","basic")
    event.create("dust_cryotheum","basic")
    event.create("dust_pyrotheum","basic")
    event.create("dust_petrotheum","basic")

})