MMEvents.registerPorts(event => {
    
    //tier1钢接口
    event.create("steel_fluid_port")
        .name("Steel Fluid")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .controllerId("mm:neutronium_charger_medium")
        .controllerId("mm:neutronium_charger_advcanced")
        .config("mm:fluid",c => {
            c.rows(1)
             .columns(1)
             .slotCapacity(2000)
        })
    event.create("steel_item_port")
        .name("Steel Item")
        .controllerId("mm:overload_infuser")
        .config("mm:item",c => {
            c.rows(1)
             .columns(3)
        })
    event.create("steel_energy_port")
        .name("Steel Energy")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:energy",c => {
            c.capacity(20000)
             .maxReceive(2000)
             .maxExtract(2000)
        })
    event.create("steel_kinetic_port")
        .name("Steel Kinetic")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:create/kinetic",c => {
            c.stress(16)
        })


    //tier2硬铅接口
    event.create("hardlead_fluid_port")
        .name("Hard Lead Fluid")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .controllerId("mm:neutronium_charger_medium")
        .controllerId("mm:neutronium_charger_advcanced")
        .config("mm:fluid",c => {
            c.rows(1)
             .columns(1)
             .slotCapacity(100000)
        })
    event.create("hardlead_item_port")
        .name("Hard Lead Item")
        .controllerId("mm:overload_infuser")
        .config("mm:item",c => {
            c.rows(2)
             .columns(3)
        })
    event.create("hardlead_energy_port")
        .name("Hard Lead Energy")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:energy",c => {
            c.capacity(200000)
             .maxReceive(10000)
             .maxExtract(10000)
        })
    event.create("hardlead_kinetic_port")
        .name("Hard Lead Kinetic")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:create/kinetic",c => {
            c.stress(32)
        })
    event.create("hardlead_air_port")
        .name("Hard Lead Air")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:pneumaticcraft/air",c => {
            c.danger(14)
            .critical(16)
            .volume(100000)
        })

        
    //tier3超致密接口
    event.create("ultra_dense_fluid_port")
        .name("Ultra Dense Fluid")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .controllerId("mm:neutronium_charger_medium")
        .controllerId("mm:neutronium_charger_advcanced")
        .config("mm:fluid",c => {
            c.rows(1)
             .columns(1)
             .slotCapacity(640000)
        })
    event.create("ultra_dense_item_port")
        .name("Ultra Dense Item")
        .controllerId("mm:overload_infuser")
        .config("mm:item",c => {
            c.rows(5)
             .columns(5)
        })
    event.create("ultra_dense_energy_port")
        .name("Ultra Dense Energy")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:energy",c => {
            c.capacity(10000000)
             .maxReceive(2000000)
             .maxExtract(2000000)
        })
    event.create("ultra_dense_kinetic_port")
        .name("Ultra Dense Kinetic")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:create/kinetic",c => {
            c.stress(128)
        })
    event.create("ultra_dense_air_port")
        .name("Ultra Dense Air")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:pneumaticcraft/air",c => {
            c.danger(22)
            .critical(24)
            .volume(500000)
        })
    event.create("ultra_dense_gas_port")
        .name("Ultra Dense Gas")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:mekanism/gas",c => {
            c.amount(48000)
        })
    event.create("ultra_dense_infuse_port")
        .name("Ultra Dense Infuse")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:mekanism/infuse",c => {
            c.amount(48000)
        })
    event.create("ultra_dense_slurry_port")
        .name("Ultra Dense Slurry")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:mekanism/slurry",c => {
            c.amount(48000)
        })
    

    //tier4过载超致密接口
    event.create("overcharged_ultra_dense_energy_port")
        .name("Overcharged-Ultra Dense Energy")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_medium")
        .config("mm:energy",c => {
            c.capacity(20000000)
             .maxReceive(20000000)
             .maxExtract(20000000)
        })
    event.create("overcharged_ultra_dense_item_port")
        .name("Overcharged-Ultra Dense Item")
        .controllerId("mm:overload_infuser")
        .config("mm:item",c => {
            c.rows(5)
             .columns(5)
        })
    event.create("overcharged_ultra_dense_fluid_port")
        .name("Overcharged-Ultra Dense Fluid")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .controllerId("mm:neutronium_charger_medium")
        .controllerId("mm:neutronium_charger_advcanced")
        .config("mm:fluid",c => {
            c.rows(1)
             .columns(1)
             .slotCapacity(720000)
        })
        event.create("overcharged_ultra_dense_kinetic_port")
        .name("Overcharged-Ultra Dense Kinetic")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:create/kinetic",c => {
            c.stress(512)
        })
    event.create("overcharged_ultra_dense_air_port")
        .name("Overcharged-Ultra Dense Air")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:pneumaticcraft/air",c => {
            c.danger(30)
            .critical(32)
            .volume(500000)
        })
    event.create("overcharged_ultra_dense_gas_port")
        .name("Overcharged-Ultra Dense Gas")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:mekanism/gas",c => {
            c.amount(720000)
        })
    event.create("overcharged_ultra_dense_infuse_port")
        .name("Overcharged-Ultra Dense Infuse")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:mekanism/infuse",c => {
            c.amount(720000)
        })
    event.create("overcharged_ultra_dense_slurry_port")
        .name("Overcharged-Ultra Dense Slurry")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:mekanism/slurry",c => {
            c.amount(720000)
        })
    

    //tier5质子接口
    event.create("protonium_fluid_port")
        .name("Protonium Fluid")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .controllerId("mm:neutronium_charger_medium")
        .controllerId("mm:neutronium_charger_advcanced")
        .config("mm:fluid",c => {
            c.rows(1)
             .columns(1)
             .slotCapacity(1280000)
        })
    event.create("protonium_item_port")
        .name("Protonium Item")
        .controllerId("mm:overload_infuser")
        .config("mm:item",c => {
            c.rows(7)
             .columns(7)
        })
    event.create("protonium_energy_port")
        .name("Protonium Energy")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:energy",c => {
            c.capacity(1400000000)
             .maxReceive(1400000000)
             .maxExtract(1400000000)
        })
    event.create("protonium_kinetic_port")
        .name("Protonium Kinetic")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:create/kinetic",c => {
            c.stress(512)
        })
    event.create("protonium_air_port")
        .name("Protonium Air")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:pneumaticcraft/air",c => {
            c.danger(46)
            .critical(48)
            .volume(1000000)
        })
    event.create("protonium_gas_port")
        .name("Protonium Gas")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:mekanism/gas",c => {
            c.amount(102400000)
        })
    event.create("protonium_infuse_port")
        .name("Protonium Infuse")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:mekanism/infuse",c => {
            c.amount(102400000)
        })
    event.create("protonium_slurry_port")
        .name("Protonium Slurry")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:mekanism/slurry",c => {
            c.amount(102400000)
        })
    

    //一体化集成燃油发动机
    event.create("integrated_fuel_engine_item_port")
        .name("Integrated Fuel Engine Item")
        .controllerId("mm:integrated_fuel_engine")
        .config("mm:item",c => {
            c.rows(3)
             .columns(6)
        })
    event.create("integrated_fuel_engine_fluid_port")
        .name("Integrated Fuel Engine Fluid")
        .controllerId("mm:integrated_fuel_engine")
        .config("mm:fluid",c => {
            c.rows(1)
             .columns(1)
             .slotCapacity(640000)
        })
    event.create("integrated_fuel_engine_energy_port")
        .name("Integrated Fuel Engine Energy")
        .controllerId("mm:integrated_fuel_engine")
        .config("mm:energy", c => {
             c.capacity(72000000)
             .maxReceive(72000000)
             .maxExtract(72000000);
        })
    event.create("integrated_fuel_engine_kinetic_port")
        .name("Integrated Fuel Engine Kinetic")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:create/kinetic",c => {
            c.stress(16384)
        })
    event.create("integrated_fuel_engine_air_port")
        .name("Integrated Fuel Engine Air")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:pneumaticcraft/air",c => {
            c.danger(46)
            .critical(48)
            .volume(1000000)
        })
    event.create("integrated_fuel_engine_gas_port")
        .name("Integrated Fuel Engine Gas")
        .controllerId("mm:overload_infuser")
        .controllerId("mm:neutronium_charger_lesser")
        .config("mm:mekanism/gas",c => {
            c.amount(128000000)
        })
})