
#Void Crystal Ore Worldgen
[void_crystal_ore]
	#Enable/Disable Void Crystal ore
	VoidCrystalOreEnabled = true
	#Min Y level
	#Range: -64 ~ -20
	minY = -64
	#Max Y Level
	#Range: -60 ~ 0
	maxY = -54
	#Ore vein count
	#Range: 1 ~ 40
	veinCount = 20
	#Ore vein size
	#Range: 1 ~ 40
	veinSize = 3

#Apatite Block Worldgen
[apatite_block]
	#Enable/Disable Void Crystal ore
	VoidCrystalOreEnabled = false
	#Min Y level
	#Range: -16 ~ 128
	minY = 80
	#Max Y Level
	#Range: 128 ~ 320
	maxY = 128
	#Ore vein count
	#Range: 1 ~ 40
	veinCount = 1
	#Ore vein size
	#Range: 16 ~ 128
	veinSize = 16

